import { FiMessageCircle } from "react-icons/fi";

const FeedbackCard = ({ feedback }) => {
  return (
    <div className="bg-white rounded-3xl shadow-xl p-10">

      <div className="flex items-center gap-5 mb-8">

        <div className="w-16 h-16 rounded-2xl bg-indigo-100 flex items-center justify-center">

          <FiMessageCircle
            className="text-indigo-600"
            size={32}
          />

        </div>

        <div>

          <h2 className="text-3xl font-bold text-slate-800">
            AI Feedback
          </h2>

          <p className="text-slate-500 mt-1">
            Overall evaluation generated by AI
          </p>

        </div>

      </div>

      <div className="bg-slate-50 rounded-2xl p-8 border border-slate-200">

        <p className="leading-9 text-slate-700 text-lg whitespace-pre-line">
          {feedback}
        </p>

      </div>

      <div className="grid md:grid-cols-3 gap-5 mt-10">

        <div className="rounded-2xl bg-green-50 border border-green-200 p-5">

          <h3 className="font-bold text-green-700 mb-2">
            👍 What's Good
          </h3>

          <p className="text-sm text-slate-600">
            Strong skills and keywords increase your ATS score.
          </p>

        </div>

        <div className="rounded-2xl bg-yellow-50 border border-yellow-200 p-5">

          <h3 className="font-bold text-yellow-700 mb-2">
            📌 Improve
          </h3>

          <p className="text-sm text-slate-600">
            Add missing skills and quantify your achievements.
          </p>

        </div>

        <div className="rounded-2xl bg-indigo-50 border border-indigo-200 p-5">

          <h3 className="font-bold text-indigo-700 mb-2">
            🚀 Next Step
          </h3>

          <p className="text-sm text-slate-600">
            Update your resume and analyze it again for a higher ATS score.
          </p>

        </div>

      </div>

    </div>
  );
};

export default FeedbackCard;